<?php

/**
 * @file
 * Caveman filter - transforms text into caveman speech.
 */

/**
 * Implements hook_help().
 */
function caveman_help($route_name) {
  if ($route_name === 'help.page.caveman') {
    return t('This module is a text filter that turns your site into caveman-speak. Ugh! Activates on April 1st or when enabled site-wide at <a href=":url">Caveman settings</a>.', [
      ':url' => \Drupal\Core\Url::fromRoute('caveman.admin_settings')->toString(),
    ]);
  }
}
